//Home map
void init_map_home(string &cur_map, vector<vector<Entity>> &mve) {

 cur_map = 
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VXXXXXXXXXXXXXXOOXXXXXXXXXXXXV"
		"VXOOOOOSOOOOOOOOOOOOOOOOOGGGXV"
		"VXOOOOOOOOOOOOOOOOOOOOOOOGGGXV"
		"VXOOOOOOOOOOOOOOOOOOOOOOOGGGXV"  //5
		"VXOOOOOOOOOOOOOOOOOOOOOOOOOOXV"
		"VXOOOOOOOOOOOOOOOOOOOOOOOOOOXV"
		"VXOOOOOOOOOOOOOOOOOOOOOOOOOOXV"
		"VXOOOOOOOOOOOOOOOOOOOOOOOOOOXV"
		"VXOOOOOOOOOOOOOOOOOOOOOOOOOOXV"  //10
		"VXOOOOOOOOOOOOOOOOOOOOOOOOOOXV"
		"VXOOOOOOOOOOOOOOOOOOOOOOOOOOXV"
		"VXOOOOOOOOOOOOOOOOOOOOOOOOOOXV"
		"VXOOOO$%%%%^OOOOOOOOOOOOOOOOXV"
		"VXOOOO153246OOOOOOOOOOOOOOOOXV"  //15
		"VXOXXX798!@#XXXOOOOOOOOOOOOOXV"
		"VXOXDDDDDDDDDDXOOOOOOOOOOOOOXV"
		"VXOXDDDDDDDDDDXOOOOOOOOOOOOOXV"
		"VXOXDDDDDDDDDDXOOOOOOOOOOOOOXV"
		"VXOXDDDWWWDDDDXOOOOOOOOOOOOOXV"  //20
		"VXOXDDDWWWDDDDXOOOOOOOOOOOOOXV"
		"VXOXDDDWWWDDDDXOOOOOOOOOOOOOXV"
		"VXOXDDDDDDDDDDXOOOOOOTTTTTTOXV"
		"VXOXDDDDDDDDDDXOOOOOTTOOOOOOXV"
		"VXOXDDDDDDDDDDXOOOTTTOOTTTTTXV"  //25
		"VXOXDDDDDDDDDDXOOOOOTOOOOTTTXV"
		"VXOXXXXXDDXXXXXOOOTTTOOOTTTTXV"
		"VXOOOOOOOOOOOOOOOTTTOOBOOTTTXV"
		"VXXXXXXXXXXXXXXXXXXXXXXXXXXXXV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV";
}

//House map
void init_map_house(string &cur_map, vector<vector<Entity>> &mve) {
 cur_map = 
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVFFFFFFFFFFVVVVVVVVV"
		"VVVVVVVVVVVFFFFFFFFFFVVVVVVVVV"
		"VVVVVVVVVVVFFFFFFFFFFVVVVVVVVV"
		"VVVVVVVVVVVFFFFFFFFFFVVVVVVVVV"
		"VVVVVVVVVVVFFFFFFFFFFVVVVVVVVV"
		"VVVVVVVVVVVFFFFFFFFFFVVVVVVVVV"
		"VVVVVVVVVVVFFFFFFFFFFVVVVVVVVV"
		"VVVVVVVVVVVFFFFFFFFFFVVVVVVVVV"
		"VVVVVVVVVVVFFFFRYFFFFVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV"
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV";
 //rug 18 down 15 over
}